# config.py
POPULATION_SIZE = 4
ALPHA = 0.75
MUTATION_COUNT = 1

LIMIT_POPULATION_GENERATION = 100
LIMIT_FITTEST_UNCHANGED_GENERATION = 15
FITNESS_RATIO_THRESHOLD = 0.9

DB_HOST = "localhost"
DB_PORT = 9999
DB_NAME = "uvo490_3"
DB_USER = "uvo490_3"
DB_PASSWORD = "coolbird18"

TARGET_SEASON = 2  # 1=Summer, 2=Fall, 3=Fall+Winter, 4=Winter
ACADEMIC_YEAR = 2026
